modLoader = "javafml"
license = "MIT license"
loaderVersion = "[34,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "0.0.3"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "BOTH"