modLoader = "javafml"
loaderVersion = "[33,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "${file.jarVersion}"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange="[33,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2]"
ordering = "NONE"
side = "BOTH"