modLoader = "javafml"
license = "MIT license"
loaderVersion = "[37,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "0.0.5"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "BOTH"