modLoader = "javafml"
license = "MIT license"
loaderVersion = "[38,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "0.0.7"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"