modLoader = "javafml"
license = "MIT license"
loaderVersion = "[32,)"
#issueTrackerURL=""

[[mods]]
modId = "windowlogging"
version = "0.0.2"
displayName = "Windowlogging"
#updateJSONURL=""
authors = "Simibubi, Grimmauld"
description = '''
Windowlogging, ported from Create 1.14.4'''

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1]"
ordering = "NONE"
side = "BOTH"